resources:
  jobs:
    train:
      name: train

      email_notifications:
        on_failure:
          - himanshu.bajpai@tigeranalytics.com

      tasks:
        - task_key: FeaturePipeline_FT
          notebook_task:
            notebook_path: ../notebooks/FeaturePipeline_FT.py
            base_parameters:
              env: dev
              task: fe
          existing_cluster_id : 0626-090904-18ykd8d0
        - task_key: FeaturePipeline_GT
          notebook_task:
            notebook_path: ../notebooks/FeaturePipeline_GT.py
            base_parameters:
              env: dev
              task: fe
          existing_cluster_id : 0626-090904-18ykd8d0
        - task_key: Train
          depends_on:
          - task_key: Feature_Pipeline_GT
          - task_key: Feature_Pipeline_FT
          notebook_task:
            notebook_path: ../notebooks/Train.py
            base_parameters:
              env: dev
          existing_cluster_id : 0626-090904-18ykd8d0